[package]
name = "ew_bit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jars = "0.1.1"
serde_json = "1.0.108"